version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_EMAIL=admin@example.com
      - N8N_PASSWORD=password123
      - N8N_FIRST_NAME=Admin
      - N8N_LAST_NAME=User
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Tokyo
      - N8N_API_DISABLED=false
      - N8N_PUBLIC_API_DISABLED=false
      - N8N_PUBLIC_API_ENDPOINT_DISABLED=false
      - N8N_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNDRiYzk2Zi1hODUxLTQwNjYtOTMyYy0xMjc1ZjgxYTc2YWEiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzUyODI0NjYwLCJleHAiOjE3NjA1ODcyMDB9.TIypgAhLqh6YvtcCgKJYe1skuzwcS_8i_RQP-Lkx1wE
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

volumes:
  n8n_data:
    external: false